// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUIp1yEv3uIAiyvpZcpeFJAJYXkf3tXtk',
    appId: '1:52541522511:web:0f08e2dbd773d05b71203a',
    messagingSenderId: '52541522511',
    projectId: 'music-app-92ecf',
    authDomain: 'music-app-92ecf.firebaseapp.com',
    storageBucket: 'music-app-92ecf.appspot.com',
    measurementId: 'G-C35Q4JEV4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUwolGx_DogRizAWmGhHqs9ny06qln1gM',
    appId: '1:52541522511:android:2d077dd2d4cebcdd71203a',
    messagingSenderId: '52541522511',
    projectId: 'music-app-92ecf',
    storageBucket: 'music-app-92ecf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDju30kxZeZDYh4PijsjMB2cvyxqDJ3ngQ',
    appId: '1:52541522511:ios:418d8f0c6ca16ef771203a',
    messagingSenderId: '52541522511',
    projectId: 'music-app-92ecf',
    storageBucket: 'music-app-92ecf.appspot.com',
    iosBundleId: 'com.vote.onlineVoting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDju30kxZeZDYh4PijsjMB2cvyxqDJ3ngQ',
    appId: '1:52541522511:ios:461300d613d227cd71203a',
    messagingSenderId: '52541522511',
    projectId: 'music-app-92ecf',
    storageBucket: 'music-app-92ecf.appspot.com',
    iosBundleId: 'com.vote.onlineVoting.RunnerTests',
  );
}
